### PR TITLE
Library.py contains the library functions.

### PR DESCRIPTION
**Pull request by rameshvp09**
review it please

### CODE REVIEW

**Comment by senthilksk78** [comment]
These are the comments :  
- use the comments methodology for the function as done in MLAGSQL.py
- U are using variables like IPAddress that you are not using within the function. If the function is not complete , then finish it and check it in to this branch again and we will review it and then check it in

**Comment by ndprasad09** [comment]
Ramesh,

 You can change the code such that you also pass sHandler as argument to SendCmd function. Since we are handling different switches, sHandler will be different for each one. 
So in one file we can login into the switches that we want to debug using connect and pass the sHandler as parameter to SendCmd function. This is will come handy.

**Comment by rameshvp09** [comment]
I have done the modifications.

**Comment by senthilksk78** [comment]
Ship it !!!

**Comment by rameshvp09** [comment]
With the previous code when run for 2 inputs , the second  Sendcmd execution got hung for indefinite amount of time.This was due to  cli paging enabled in the switch. Corrected it and added a time out of 5 seconds to read until to get rid of this condition.

**Pull request merged**
